### ISSUE TITLE
Presto Issue 

### ISSUE THREAD

**Issue by imranmahalingam** [immunogenomics/presto#1]
Hello,
We have been trying to run a program which requires the "presto" package, but it is not working. We have updated our R software to the most recent version (3.6.1), and have also re-dowloaded Rpcc. An error message (see below) still shows up after the changes were made. Can you please provide some suggestions as to how to get the program working.
Thank you,
Imran
-----------------------------------------------------------------------------------------------
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘presto’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/presto’
Error: Failed to install 'scClustViz' from GitHub:
  Failed to install 'presto' from GitHub:
  (converted from warning) installation of package ‘/var/folders/_s/1w1b5qg13_j2964wrfzsl8340000gn/T//Rtmp0BtBtn/file4d272ff7bed1/presto_1.0.0.tar.gz’ had non-zero exit status

**Comment by ilyakorsunsky** [comment]
I am not sure how the scClustViz package currently installs presto as a dependency. Can you try to install presto directly with devtools? 

```
library(devtools)
install_github('immunogenomics/presto')
```

**Comment by imranmahalingam** [comment]
Thank you ilyakorsunsky, but we have already attempted to do this, and had no luck. We also tried wording it in a different way : 
devtools::install_github("immunogenomics/presto")

**Comment by ilyakorsunsky** [comment]
Can you provide some more details from the error log?

**Comment by innesbre** [comment]
Hi Ilya,
I just tried re-creating their error (R 3.6.0 in windows) and got the same failure, due to an error converted from warning that Rcpp was built in R 3.6.1.  Updating to R 3.6.1 seems to have resolved the error.  That was a bit of a surprise, since I've often used R versions behind the current version with updated packages built in newer versions of R, so I'm not sure why Rcpp didn't want to be backwards compatible (or maybe devtools doesn't tolerate that and converts warnings to errors automatically).  Either way, doesn't look like its a problem on your end.

**Comment by ilyakorsunsky** [comment]
Thanks for looking into this Brendan!
